version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.5

jobs:
  node-latest: &test
    docker:
      - image: node:latest
    # environment:
    #   COVERALLS_FLAG_NAME: node-latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: yarn test
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Creating coverage LCOV
          command: yarn ci:coverage
      - coveralls/upload:
          parallel: true
          flag_name: $CIRCLE_JOB
          verbose: true
  node-12:
    <<: *test
    docker:
      - image: node:12
    # environment:
    #   COVERALLS_FLAG_NAME: node-12
  node-10:
    <<: *test
    docker:
      - image: node:10
    # environment:
    #   COVERALLS_FLAG_NAME: node-10
  report-coverage:
    docker:
      - image: node:latest
    steps:
      - coveralls/upload:
          parallel_finished: true

  cache:
    <<: *test
    # environment:
    #   COVERALLS_FLAG_NAME: cache
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  "@bionikspoon/html-to-md":
    jobs:
      - node-latest
      - node-12
      - node-10
      - report-coverage:
          requires:
            - node-latest
            - node-12
            - node-10
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
